#!/bin/sh

# This will generate a keypair for each command line argument:
#
# Create keys named "daniel", "jacob", and "whitley"
#  % generate-lots-of-ssh-keypairs.sh daniel jacob whitley
#
# Create 100 numbered keys
#  % generate-logs-of-ssh-keypairs.sh $(seq 100)

for name in $@; do
    echo | ssh-keygen -f $name -C ${name}@autogenerated >/dev/null -f ~/.ssh/${name} 2>/dev/null
    if [ $? != 0 ]; then
        echo "[-] Key exists: $name"
    else
        echo "[+] Created $name"
    fi
done

